# Generated by Django 5.0 on 2024-01-16 11:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='shaba',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 14, 40, 33, 790299)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carddetail'),
        ),
    ]
