# Generated by Django 5.0 on 2024-02-09 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_carddetail_card_number_alter_carddetail_shaba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemember',
            name='answer',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=7),
        ),
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 9, 57, 24, 732606)),
        ),
    ]
