# Generated by Django 5.0 on 2024-04-18 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentdebttrackingcode_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 14, 35, 41, 488775)),
        ),
    ]
