# Generated by Django 5.0 on 2024-04-14 15:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitemember_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.carddetail'),
        ),
        migrations.AddField(
            model_name='loan',
            name='method',
            field=models.CharField(blank=True, choices=[('CUT', 'CUT'), ('IR', 'IR')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 18, 30, 39, 236242)),
        ),
    ]
