# Generated by Django 5.0 on 2024-04-16 15:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loan_card_loan_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 13, 57, 772558)),
        ),
    ]
