# Generated by Django 5.0 on 2024-04-18 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentdebttrackingcode_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdebttrackingcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 22, 42, 1, 187555)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wage_percentage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.transactionfee'),
        ),
    ]
