# Generated by Django 5.0 on 2024-04-18 10:50

import datetime
import django.db.models.deletion
import gamesplayed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_pot', models.IntegerField()),
                ('boss_kill', models.IntegerField()),
                ('run_notes', models.CharField(blank=True, max_length=555, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], max_length=1)),
                ('characters_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('paid_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CutInIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Close')], max_length=1)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 4, 18, 14, 20, 22, 629060))),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ratio', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='RunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('community', models.FloatField(default=63.5)),
                ('guild', models.FloatField(default=27.5)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_boss', models.IntegerField(default=0)),
                ('multiplier', models.FloatField(default=1.0)),
                ('cut', models.IntegerField(default=0)),
                ('alt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.alt')),
                ('attendane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.attendance')),
                ('payment_character', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_character', to='accounts.alt')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=gamesplayed.models.Role.get_default_role, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamesplayed.role')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentRealm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.attendance')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.realm')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='cycle',
            field=models.ForeignKey(default=gamesplayed.models.Cycle.create_or_get_latest, on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.cycle'),
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster', models.IntegerField(default=0)),
                ('gold_collector', models.IntegerField(default=0)),
                ('guild_bank', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('in_house_customer_pot', models.IntegerField(default=0)),
                ('refunds', models.IntegerField(default=0)),
                ('attendance', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='CutDistributaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.IntegerField(default=0)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.attendance')),
                ('total_guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.guild')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('string', models.CharField(blank=True, max_length=256, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.cycle')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesplayed.attendancedetail')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='run_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesplayed.runtype'),
        ),
    ]
