# Generated by Django 5.0 on 2024-01-16 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplayed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 14, 40, 33, 790299)),
        ),
    ]
