# Generated by Django 5.0 on 2024-04-18 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplayed', '0002_alter_cycle_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 14, 35, 41, 504398)),
        ),
    ]
