# Generated by Django 5.0 on 2024-02-09 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplayed', '0002_alter_cycle_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 9, 57, 24, 748211)),
        ),
    ]
